version: 2.0
update:
  - "git pull origin main"  # Replace 'main' with your branch name

hooks:
  post_update:
    - "source /home/football/virtualenv/repositories/footballerdirectory/3.9/bin/activate && cd /home/football/repositories/footballerdirectory && pip install -r requirements.txt"
    - "source /home/football/virtualenv/repositories/footballerdirectory/3.9/bin/activate && cd /home/football/repositories/footballerdirectory && python manage.py migrate"
    - "source /home/football/virtualenv/repositories/footballerdirectory/3.9/bin/activate && cd /home/football/repositories/footballerdirectory && python manage.py collectstatic --noinput"
    - "touch /home/football/repositories/footballerdirectory/passenger_wsgi.py"  # This will restart the app
