name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to cPanel
      run: |
        # Use sshpass to handle the passphrase
        sshpass -p "${{ secrets.SSH_PASSPHRASE }}" ssh -o StrictHostKeyChecking=no ${{ secrets.CPANEL_SSH_USER }}@${{ secrets.CPANEL_SERVER }} << 'EOF'
          cd /home/football/repositories/footballerdirectory  # Adjust this path to your repo

          # Pull latest changes from GitHub
          git pull origin main  # Adjust branch name if necessary

          # Activate virtual environment and run post-update tasks
          source /home/football/virtualenv/repositories/footballerdirectory/3.9/bin/activate  # Adjust the path to your virtualenv
          
          # Install dependencies
          pip install -r requirements.txt
          
          # Run migrations
          python manage.py migrate
          
          # Collect static files
          python manage.py collectstatic --noinput
          
          # Restart the app
          touch /home/football/repositories/footballerdirectory/config/passenger_wsgi.py  # Adjust if necessary
        EOF
