name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to cPanel
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes ${{ secrets.CPANEL_SSH_USER }}@${{ secrets.CPANEL_SERVER }} << 'EOF'
          cd /home/***/repositories/***erdirectory
          
          # Pull latest changes from GitHub
          git pull origin main

          # Activate virtual environment and run post-update tasks
          source /home/***/virtualenv/repositories/***erdirectory/3.9/bin/activate
          
          # Install dependencies
          pip install -r requirements.txt
          
          # Run migrations
          python manage.py migrate
          
          # Collect static files
          python manage.py collectstatic --noinput
          
          # Restart the app
          touch /home/***/repositories/***erdirectory/config/passenger_wsgi.py
        EOF

